name: 'testmonitoring'
version: '1.0.0'
config-version: 2

profile: 'testmonitoring'

model-paths: ["models"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
test-paths: ["tests"]
analysis-paths: ["analysis"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  testmonitoring:
    staging:
      +materialized: view
    marts:
      +materialized: table
  elementary:
    +schema: elementary
